import { Icon } from "./ui/Icon";
import {
  House,
  MagnifyingGlass,
  Receipt,
  User,
  ShoppingBag,
  ArrowLeft,
  Plus,
  Minus,
  Heart,
  Star,
  ChatCircle,
  Bell,
  Copy,
  MapPin,
  Funnel,
  Clock,
  Eye,
  EyeSlash,
  CheckCircle,
  SquaresFour,
  Users,
  Gear,
  SignOut,
  Package,
  NavigationArrow,
  Storefront,
  ChefHat,
  Trash,
  PencilSimple,
  CreditCard,
  Bank,
  IdentificationBadge,
  ShieldCheck,
  Calendar,
  ChartLineUp,
  Cube,
  Wallet,
  List,
  ArrowClockwise,
  ChatCircleDots,
  PaperPlaneTilt,
  VideoCamera,
  Phone,
  Lock,
  Checks,
  Camera,
} from "phosphor-react-native";

// Domain-grouped icons (Phosphor). Import glyphs from here, never raw.
// Names stay stable so art direction can change without touching screens.
export {
  House as Home01Icon,
  MagnifyingGlass as Search01Icon,
  Receipt as ReceiptIcon,
  User as UserIcon,
  ShoppingBag as ShoppingBag02Icon,
  ArrowLeft as ArrowLeft01Icon,
  Plus as PlusSignIcon,
  Minus as MinusSignIcon,
  Heart as FavouriteIcon,
  Star as StarIcon,
  ChatCircle as BubbleChatIcon,
  Bell as Notification01Icon,
  Copy as Copy01Icon,
  MapPin as MapPinIcon,
  Funnel as FilterIcon,
  Clock as Clock01Icon,
  Eye as EyeIcon,
  EyeSlash as EyeOffIcon,
  CheckCircle as CheckmarkCircle01Icon,
  SquaresFour as DashboardSquare01Icon,
  Users as UsersIcon,
  Gear as Settings01Icon,
  SignOut as Logout01Icon,
  Package as Package01Icon,
  NavigationArrow as Navigation01Icon,
  Storefront as Store01Icon,
  ChefHat as ChefHatIcon,
  Trash as Delete02Icon,
  PencilSimple as Edit02Icon,
  CreditCard as CreditCardIcon,
  Bank as BankIcon,
  IdentificationBadge as IdentificationIcon,
  ShieldCheck as ShieldCheckIcon,
  Calendar as Calendar01Icon,
  ChartLineUp as ChartLineIcon,
  Cube as DeliveryBox01Icon,
  Wallet as Wallet01Icon,
  List as ListViewIcon,
  ArrowClockwise as RefreshIcon,
  ChatCircleDots as BubbleChatNotificationIcon,
  Wallet as BanknoteIcon,
  PaperPlaneTilt as SentIcon,
  VideoCamera as Video01Icon,
  Phone as PhoneIcon,
  Lock as LockIcon,
  Checks as CheckCheckIcon,
  Camera as Camera01Icon,
};

// Tab-bar compatible renderer with the app's default stroke.
export function ic(glyph: any) {
  return (props: { color: string; size: number; strokeWidth?: number }) => (
    <Icon
      icon={glyph}
      color={props.color}
      size={props.size}
      strokeWidth={props.strokeWidth ?? 1.9}
    />
  );
}
